{
 "title": "Span Metric Service Performance Monitoring",
 "description": "SPM using Generated RED (Request, Error, Duration) Spanmetrics",
 "tags": [
  "otel",
  "traces",
  "spanmetrics"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(traces_spanmetrics_calls_total,service_name)"
    }
   },
   {
    "name": "operation",
    "query": {
     "query": "label_values(traces_spanmetrics_calls_total{service_name=\"$service\", span_kind=\"SPAN_KIND_SERVER\"},span_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.95, sum(rate(traces_spanmetrics_latency_bucket{service_name=\"$service\"}[$__rate_interval])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(.75, sum(rate(traces_spanmetrics_latency_bucket{service_name=\"$service\"}[$__rate_interval])) by (le))",
     "legendFormat": "75th"
    },
    {
     "expr": "histogram_quantile(.50, sum(rate(traces_spanmetrics_latency_bucket{service_name=\"$service\"}[$__rate_interval])) by (le))",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "Error Rate (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(traces_spanmetrics_calls_total{service_name=\"$service\", status_code=\"STATUS_CODE_ERROR\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "Error Rate"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(traces_spanmetrics_calls_total{service_name=\"$service\"}[$__rate_interval]))",
     "legendFormat": "req/s"
    }
   ]
  },
  { "title": "$operation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "operation" },
  {
   "title": "P95 Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(.95, sum(rate(traces_spanmetrics_latency_bucket{service_name=\"$service\", span_name=\"$operation\"}[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate (%)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(traces_spanmetrics_calls_total{service_name=\"$service\", span_name=\"$operation\", status_code=\"STATUS_CODE_ERROR\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(traces_spanmetrics_calls_total{service_name=\"$service\", span_name=\"$operation\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}