services:
  ping1:
    build: .
    hostname: ping12
    container_name: ping1
    networks:
      - red_ping
    entrypoint: ["/bin/bash"]
    tty: true
  ping2:
    build: .
    hostname: ping22
    container_name: ping2
    networks:
      - red_ping
    entrypoint: ["/bin/bash"]
    tty: true


networks:
  red_ping:
    external: true