services:
  garage:
    image: dxflrs/garage:v2.2.0
    container_name: garage
    restart: unless-stopped
    ports:
      - "3900:3900"   # API S3
      - "3901:3901"   # RPC interna
      - "3902:3902"   # Web?
    volumes:
      - ./data:/var/lib/garage
      - ./config/garage.toml:/etc/garage.toml