services:
  jenkins_controller:
    #image: jenkins/jenkins:lts-jdk21
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    user: root
    container_name: jenkins_controller
    ports:
      - 8081:8080
      - 50002:50000
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - ./id_ed25519:/root/.ssh/id_ed25519
      - ./id_ed25519.pub:/root/.ssh/id_ed25519.pub
      - /var/run/docker.sock:/var/run/docker.sock
  jenkins_agent:
    #image: jenkins/ssh-agent:jdk21
    build:
      context: .
      dockerfile: Dockerfile.agent
    privileged: true
    user: root
    container_name: jenkins_agent
    expose:
      - 22
    volumes:
      - ./id_ed25519.pub:/home/jenkins/.ssh/authorized_keys
      - ./jenkins_home_agent:/home/jenkins
