services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./config/mongod.conf:/etc/mongod.conf:ro
      # Persistencia de datos
      - ./data:/data/db
    command: [ "mongod", "--config", "/etc/mongod.conf" ]